'********************************************************************
'
' C-Control/BASIC       001.BAS
'
' Systemvoraussetzungen:
'
' - serielle Verbindung zum PC
' - Terminalprogramm
'
' Schwerpunkte:
'
' - Textausgabe mit PRINT
'
'********************************************************************

' --- Programmoperationen -------------------------------------------

'Programmtitel ausgeben 
print "C-Control/BASIC      001.BAS"
print "============================"

'Leerzeile
print

'noch ein Text
print "Hallo!"

'mehrere Ausgaben in einer Zeile
print "Hallo!";
print "Hallo!";
print "Hallo!"

' zusammengefasst in einem Befehl
print "Hallo!"; "Hallo!"; "Hallo!"

' mit Tabulatoren dazwischen
print "Hallo!", "Hallo!", "Hallo!"

' noch eine Leerzeile ausgeben und Programmende
print
end

' Wenn der Starttaster jetzt noch gedrueckt ist,
' beginnt das Programm wieder von vorn!


